// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIP2EDuZdFoWifISHPUqGZsUFD_QYDqAY',
    appId: '1:253875326987:web:7f8ecc2b908d817012370e',
    messagingSenderId: '253875326987',
    projectId: 'myekegai',
    authDomain: 'myekegai.firebaseapp.com',
    storageBucket: 'myekegai.appspot.com',
    measurementId: 'G-6YX48ZMVJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlkxrECXccr9DINt6aOheT9TEIAaF9SQ',
    appId: '1:253875326987:android:4d9f575f050a771a12370e',
    messagingSenderId: '253875326987',
    projectId: 'myekegai',
    storageBucket: 'myekegai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArw3PxDETJnfIOAAaC7Bf0IqBVisw9P5w',
    appId: '1:253875326987:ios:ebec9ba01351e57912370e',
    messagingSenderId: '253875326987',
    projectId: 'myekegai',
    storageBucket: 'myekegai.appspot.com',
    androidClientId: '253875326987-1oa4ld5mm6k9php5nrfngv3bpfkmbe7l.apps.googleusercontent.com',
    iosClientId: '253875326987-90d4ti0108h5f53b2rl0pbnr57vvh5ts.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArw3PxDETJnfIOAAaC7Bf0IqBVisw9P5w',
    appId: '1:253875326987:ios:ebec9ba01351e57912370e',
    messagingSenderId: '253875326987',
    projectId: 'myekegai',
    storageBucket: 'myekegai.appspot.com',
    androidClientId: '253875326987-1oa4ld5mm6k9php5nrfngv3bpfkmbe7l.apps.googleusercontent.com',
    iosClientId: '253875326987-90d4ti0108h5f53b2rl0pbnr57vvh5ts.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
